amcl:
  ros__parameters:
    use_sim_time: true
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    update_min_d: 0.25
    update_min_a: 0.2

planner_server:
  ros__parameters:
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.25
      use_astar: true
      allow_unknown: true

controller_server:
  ros__parameters:
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller/RegulatedPurePursuitController"
      desired_linear_vel: 0.4
      max_lookahead_dist: 1.5
      lookahead_time: 1.5
      min_lookahead_dist: 0.3
      use_velocity_scaled_lookahead_dist: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_nav_through_poses_bt_xml: "nav_through_poses_bt.xml"
    default_nav_to_pose_bt_xml: "nav_to_pose_bt.xml"

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother/SimpleSmoother"
      tolerance: 1.0

map_server:
  ros__parameters:
    yaml_filename: "warehouse_map.yaml"

recoveries_server:
  ros__parameters:
    recovery_plugins: ["Spin", "BackUp", "Wait"]
    Spin:
      plugin: "nav2_recoveries/Spin"
    BackUp:
      plugin: "nav2_recoveries/BackUp"
    Wait:
      plugin: "nav2_recoveries/Wait"

local_costmap:
  ros__parameters:
    update_frequency: 5.0
    publish_frequency: 2.0
    global_frame: odom
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["voxel_layer", "inflation_layer"]
    voxel_layer:
      plugin: "nav2_costmap_2d::VoxelLayer"
      z_voxels: 10
      origin_z: 0.0
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6

global_costmap:
  ros__parameters:
    update_frequency: 2.0
    publish_frequency: 1.0
    global_frame: map
    robot_base_frame: base_link
    resolution: 0.05
    plugins: ["static_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
      inflation_radius: 0.6
