slam_toolbox:
  ros__parameters:
    use_sim_time: true
    publish_map: true
    map_file_name: "warehouse_map"
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.4
    transform_publish_period: 0.05
    tf_buffer_duration: 30.0
    enable_loop_closure: true
    loop_closure_threshold: 0.3
    loop_closure_search_radius: 6.0
    mode: "mapping"
    map_start_pose: [0.0, 0.0, 0.0]
    scan_topic: "/scan"
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
