use_sim_time: true

amcl:
  ros__parameters:
    min_particles: 100
    max_particles: 2000
    kld_err: 0.05
    kld_z: 0.99
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 2
    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0
    laser_min_range: 0.12
    laser_max_range: 3.5
